spring:
  security:
    permit_paths: /**
    cors:
      enabled: false
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/checkman
    username: checkman
    password: checkman
    pool:
      enabled: true

server:
  port: 9002
  ssl:
    enabled: false

logging:
  level:
    tracer: TRACE
